### ISSUE TITLE
Add version requirements to docs

### ISSUE THREAD

**Issue by antonioortegajr** [antonioortegajr/github-users-by-location#20]
The readme should list requirements for the project

Like:

- node version
- teraform version

**Comment by akj2018** [comment]
I would like to work on this issue. Please assign me.

**Comment by antonioortegajr** [comment]
Assigned @akj2018

**Comment by antonioortegajr** [comment]
@akj2018 should I un assign this? Just checking in.

**Comment by akj2018** [comment]
Apologies for being inactive @antonioortegajr . 

I am on it. Will complete it asap. Thank you!

**Comment by akj2018** [comment]
Hi @antonioortegajr 

I have mentioned the Version Requirements in the Pull Request #25 

Let me know if it requires any changes. 

Thanks
