### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by antonioortegajr** [antonioortegajr/github-users-by-location#23]
Add a Contribution section in the Main readme.md at the root level.

Add this link in whatever copy you create to let people know where to check for issues.

https://github.com/antonioortegajr/github-users-by-location/contribute

**Comment by aasthak108** [comment]
Hello @antonioortegajr I want to work on this issue. Can you please assign me this issue

**Comment by antonioortegajr** [comment]
@aasthak108 assigned to you

**Comment by aasthak108** [comment]
@antonioortegajr  thank you for assigning this issue to me, I am working on this issue.

**Comment by aasthak108** [comment]
@antonioortegajr  hello, I have raised a pull request regarding the documentation issue. I have added the new Contribution section in the README.md file with the valid link, you can check it out. Thank you!

**Comment by aasthak108** [comment]
Hello, @antonioortegajr  I have added the new section Contribution to the README.md file with the link provided for the users to check the issues. You can check this out. Thank you!

**Comment by antonioortegajr** [comment]
Resolved in https://github.com/antonioortegajr/github-users-by-location/pull/24
